### ISSUE TITLE
More detailed installation guide

### ISSUE THREAD

**Issue by zapik** [larshp/abaplint-eclipse#5]
Hello, I actually want to try your great abaplint project as plugin for eclipse, but I am stuck (as I am not anyhow familiar with plugin concepts nor TS nor Node...).

So I started with your instructions:
1. Import all three projects into Eclipse  _- so imported as GIT project, now have abaplint.site, com.abaplint.eclipse and org.abaplint.eclipse  in Project Explorer - I assume this is the point here_
2. build project abaplint
3. copy web/script/bundle.js from the abaplint project to org.abaplint.eclipse/src/bundle/

but I am not sure how to perform step 2?  I assumed that 

> npm test

should do the work, but I don't see web/script/bundle.js 

Could you help?
Thank you.

**Comment by larshp** [comment]
actually I dont think abaplint-eclipse works anymore, plus back in 2016 it was running really slow(Javascript in Java), since then a lot more code has been added

will add a deprecation notice in the readme, sorry

plus the filenames does not follow the abapGit standard, so abaplint will not work on it anymore

**Comment by larshp** [comment]
currently abaplint works best with Visual Studio Code

**Comment by larshp** [comment]
also note https://github.com/larshp/abapOpenChecks contains a lot of the same checks as abaplint, plus more

**Comment by zapik** [comment]
aah, ok then :) Thank you very much for your time!

Do you by a chance know if there is any ABAP source code formatter (for eclipse) which could automatically enforce some custom rules (like where to put brackets etc.) not just simple alignment and changing case for keywords (so to be better than ABAP Pretty Print) ?

**Comment by larshp** [comment]
there is some work at https://github.com/flaiker/prettier-printer but its not done AFAIK

I think the power tools of the future will be outside of Eclipse, much like [eslint](https://eslint.org) and similar
