### ISSUE TITLE
Deprecated but is there an alternative?

### ISSUE THREAD

**Issue by Tiberriver256** [larshp/abaplint-eclipse#6]

**Comment by larshp** [comment]
pull requests welcome, I currently dont have the time to maintain it, plus I do not use Eclipse

the Java built-in javascript engine is quite slow, so it ends up not running very well. Plus abaplint works on the files, which all does not exist in a Eclipse ABAP dev setup


My current recommendation would be use https://github.com/larshp/abapOpenChecks it has much of the same rules, and setup abaplint to run in a CI setup, multiple examples linked from https://github.com/abaplint/abaplint

**Comment by Tiberriver256** [comment]
Cool. Thank you. What editor do you use?

**Comment by larshp** [comment]
SE80 for ABAP development 😁 

vscode for js/typescript
